cargo-features = ["panic-immediate-abort"]

[package]
name = "ch32-util"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
harness = false

[features]
default = ["debug","ch32v003f4u6","platform-spin"]
debug = []
platform-spin = ["embassy-executor/platform-spin"]
platform-riscv32 = ["embassy-executor/platform-riscv32"]
# TSSOP-20
ch32v003f4u6 = ["ch32-hal/ch32v003f4u6", "ch32-metapac/ch32v003f4u6"]
# SOP-8
ch32v003j4m6 = ["ch32-hal/ch32v003j4m6", "ch32-metapac/ch32v003j4m6"]
# SOP-16
ch32v003a4m6 = ["ch32-hal/ch32v003a4m6", "ch32-metapac/ch32v003a4m6"]

[dependencies]
ch32-hal = { 
    git = "https://github.com/ch32-rs/ch32-hal",
    version = "0.1.0",
    features = ["memory-x","embassy","time-driver-tim2","rt","exti"],
    default-features = false,
}
ch32-metapac = { version = "0.1.0", 
    default-features = false,
}

embassy-embedded-hal = "0.6.0"
embassy-executor = { version = "0.10.0", features = [
    "executor-thread",
] }
embassy-sync = "0.8.0"
# embassy-time = { version = "0.5.1", features = ["tick-hz-32_768"] }
embassy-time = { version = "0.5.1" }

# This is okay because we should automatically use whatever ch32-hal uses
qingke = "0.7"
# Dont use highcode feature (uses too nuch RAM)
qingke-rt = { version = "0.7", features=[] }

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"

# portable-atomic = { version = "1.14.0", features = ["unsafe-assume-single-core"] }
# (Need critical-section for fetch_add etc)
portable-atomic = { version = "1.14.0", features = ["critical-section"] }
ufmt = { version = "0.2.0" }
heapless = { version = "0.9.3", features = ["ufmt"] }
static_cell = "2.1.1"
critical-section = "1.2.0"
embassy-futures = "0.1.2"

[profile.release]
panic = "immediate-abort"
opt-level = "z"
lto = "fat"
codegen-units = 1
debug = 2              # free: DWARF isn't ALLOC, never reaches flash
overflow-checks = false
debug-assertions = false
incremental = false
strip = false          # keep symbols for wlink regs → dpc lookup

[profile.dev]
overflow-checks = false

